<a href="https://colab.research.google.com/github/Haricharanpampad/my-projects/blob/main/Diabetes_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler #for standardizing the data
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import svm # support vector machine also logistic regree can be used but for small datasets with complex features
#we use svm it hard classifies things with a margin line how far the point is whether its true or not true thats it

In [ ]:
diabetes_dataset=pd.read_csv('/content/diabetes (1).csv')

In [ ]:
diabetes_dataset.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
# after importing check the outcome categories have equal counts like diabetic 50% and non diabetic also be like 50%
diabetes_dataset['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

0->non diabetic
1->diabetic

getting mean values of all features mean grouped by labels outcomes for cool understanding

In [ ]:
diabetes_dataset.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

In [ ]:
#separating features and labels
X=diabetes_dataset.drop(columns='Outcome',axis=1)
Y=diabetes_dataset['Outcome']
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

Standardizing the data cuz all features are in different ranges
using StandardScaler funtion

In [ ]:
scaler=StandardScaler()
scaler.fit(X)

StandardScaler()

transforming the standardized data

In [ ]:
standardized_data=scaler.transform(X)
#or  we can fit and transform data at a time by "scaler.fit_transform()"

In [ ]:
print(standardized_data)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]

In [ ]:
X=standardized_data
Y=diabetes_dataset['Outcome']

train test split

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)
# stratify funtion is used on y because
#this funtion used to spread the data in eqally
#like for y outcomes 1,0 should be spreded in x_train and x_test
#and x_test proposionally

In [ ]:
X.shape,X_train.shape,X_test.shape

((768, 8), (614, 8), (154, 8))

Traning model with support vector machine svm model

In [ ]:
classifier=svm.SVC(kernel='linear') #loading the machine

In [ ]:
#training the svm classifier

In [ ]:
classifier.fit(X_train,Y_train)

SVC(kernel='linear')

model evaluation

In [ ]:
X_train_prediction=classifier.predict(X_train)

In [ ]:
x_train_accuracy=accuracy_score(X_train_prediction,Y_train)

In [ ]:
x_train_accuracy

0.7866449511400652

In [ ]:
X_test_prediction=classifier.predict(X_test)
X_test_accuracy=accuracy_score(X_test_prediction,Y_test)

In [ ]:
X_test_accuracy

0.7727272727272727

In [ ]:
scaler.fit(X)

StandardScaler()

Making a predictive system

In [ ]:
input_data=(3,111,56,39,0,30.1,0.557,30)
# changing the input data to numpy array
input_data_as_np=np.asarray(input_data)
input_reshaped=input_data_as_np.reshape(1,-1)
# now lets standardize the data
std_data=scaler.transform(input_reshaped)
print(std_data)

prediction=classifier.predict(std_data)
print(prediction)

[[3.00000000e+00 1.11000000e+02 5.60000000e+01 3.90000000e+01
  3.00685403e-17 3.01000000e+01 5.57000000e-01 3.00000000e+01]]
[1]